apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-deployment
  namespace: doctor-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doctor
  template:
    metadata:
      labels:
        app: doctor
    spec:
      containers:
      - name: doctor-container
        image: siva8466/online-doctor-app:v1
        ports:
        - containerPort: 8000
