version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: always
