apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: doctor-app
spec:
  selector:
    app: doctor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
