apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doctor-app
  template:
    metadata:
      labels:
        app: doctor-app
    spec:
      containers:
        - name: doctor-app
          image: gcr.io/YOUR_PROJECT_ID/doctor-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis-service"
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-app-service
spec:
  selector:
    app: doctor-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
