name: CI/CD Pipeline for Doctor App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          echo "No unit tests yet"

      - name: Build & Push Docker Image to Artifact Registry
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/$praxis-gasket-465908-h5/doctor-app/doctor-app
          docker build -t $IMAGE_NAME .
          echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
          docker push $IMAGE_NAME

      - name: Start Flask app in background
        run: |
          python app.py &
          sleep 5

      - name: Health check
        run: |
          curl --fail http://127.0.0.1:5000 || exit 1

      - name: Stop Flask app
        run: |
          pkill -f app.py
