name: CI/CD for Online Doctor App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🚦 Run Flask app test
      run: |
        python app.py &
        sleep 5
        curl --fail http://localhost:8000 || exit 1

    - name: 🔐 Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 🔧 Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: 🐳 Build and Push Docker image to GCR
      run: |
        IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/doctor-app:${{ github.sha }}
        docker build -t $IMAGE .
        echo $IMAGE > image-url.txt
        gcloud auth configure-docker --quiet
        docker push $IMAGE

    - name: 📂 Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: ☁️ Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --zone ${{ secrets.GCP_ZONE }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

    - name: 🚀 Deploy to GKE
      run: |
        IMAGE=$(cat image-url.txt)
        kubectl set image deployment/doctor-deployment doctor-container=$IMAGE
        kubectl rollout status deployment/doctor-deployment
