name: CI/CD for Online Doctor App with GKE

on:
  push:
    branches: [main]

jobs:
  build-deploy-gke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          echo "No unit tests defined yet"

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/online-doctor-app
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Set up GCP authentication
        run: |
          echo "${{ secrets.GKE_SA_KEY }}" | base64 -d > ${{ runner.temp }}/gke-key.json
        env:
          GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up kubectl
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
